config/routes.rb
Rails.application.routes.draw do
  root 'posts#top'
  resources :users
  get '/login', to: 'users#enter', as: :login
  post '/login', to: 'users#login'
  delete '/logout', to: 'users#logout', as: :logout
  get '/users/(:id)/delete', to:'users#destroy_confirmation', as: :delete_user

  get '/top', to: 'posts#top', as: :top
  get '/posts/new', to: 'posts#new', as: :new_post
  post 'posts/new', to: 'posts#create'
  get '/posts/(:id)', to: 'posts#show', as: :post
  delete '/posts/(:id)', to: 'posts#destroy', as: :delete_post
  patch '/posts/(:id)', to: 'posts#update'
  get '/posts/(:id)/edit', to: 'posts#edit', as: :edit_post
  post '/readme', to: 'posts#readme', as: :readme
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  has_many :posts, dependent: :destroy
  validates :name, presence: true, uniqueness: { case_sensitive: false }, length: { maximum: 255 }
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }, allow_nil: true

  class << self

    def digest(string)
      cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                    BCrypt::Engine.cost
      BCrypt::Password.create(string, cost: cost)
    end

  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user, only: [:index, :show, :logout]
  before_action :correct_user, only: [:edit, :update, :destroy_confirmation, :destroy]
  before_action :logged_out_user, only: [:enter, :login, :new, :create]
  before_action :root_user, only: [:new, :create]

  # GET /users or /users.json
  def index
    @users = User.all
  end

  # GET /users/1 or /users/1.json
  def show
    @user = User.find_by(id: params[:id])
    @posts = @user.posts.order('created_at desc').paginate(page: params[:page])
  end

  # GET /users/new
  def new
  end

  # POST /users or /users.json
  def create
    @user = User.new(user_params)
    if @user.save
      log_in(@user)
      flash[:success] = "User was successfully created."
      redirect_to @user
    else
      flash[:danger] = @user.error_print("Fail to signup...")
      redirect_to new_user_path
    end
  end

  def enter
  end

  def login
    name = params[:name]
    @user = User.find_by(name: name)
    if @user.nil?
      flash.now[:danger] = "No user named #{name} was found..."
      render 'enter' and return
    elsif !@user.authenticate(params[:password])
      flash.now[:danger] = "Password is incorrect."
      render 'enter' and return
    else
      log_in(@user)
      flash[:success] = "Hello, #{@user.name}."
      redirect_to @user
    end
  end

  def logout
    log_out
    redirect_to top_url
  end

  # GET /users/1/edit
  def edit
  end

  # PATCH/PUT /users/1 or /users/1.json
  def update
    if @user.update(user_params)
      flash[:success] = "User was successfully updated."
      redirect_to @user and return
    else
      flash[:danger] = @user.error_print("Fail to update...")
      redirect_to edit_user_path and return
    end
  end

  def destroy_confirmation
  end

  def destroy
    name = params[:name_confirmation]
    if name != @user.name
      flash[:info] = "The name could not be confirmed."
      redirect_to delete_user_url(@user)
    else
      if @user.destroy
        log_out
        flash[:danger] = "Your account is permanently deleted... Good-bye #{name}."
        redirect_to top_url
      else
        flash[:info] = @user.error_print("Fial to delete...")
        redirect_to delete_user_url(@user)
      end
    end
  end

  private

    # Only allow a list of trusted parameters through.
    def user_params
      params.require(:user).permit(:name, :password, :password_confirmation)
    end

    def logged_in_user
      @user = User.find_by(id: current_user.id) if logged_in?
      if @user.nil?
        flash[:danger] = "Need to log in."
        redirect_back_or(top_url) and return false
      end
      return true
    end

    def correct_user
      if !logged_in_user || @user.id != params[:id].to_i
        flash[:danger] = "Incorrect user's operation."
        redirect_back_or(users_url)
      end
    end

    def logged_out_user
      if logged_in?
        flash[:danger] = "Still logged in."
        redirect_back_or(top_url)
      else
        @user = User.new
      end
    end

    def root_user
      flash[:info] = "Sign-up function is now restricted."
      redirect_to top_url
    end
end

app/helpers/users_helper.rb
module UsersHelper
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def current_user?(user)
    !user.nil? && user == current_user
  end

  def log_in(user)
    session[:user_id] = user.id
  end

  def logged_in?
    current_user.present?
  end

  def log_out
    session.delete(:user_id)
    @current_user = nil
  end

  def redirect_back_or(default)
    redirect_to request.referer || default
  end

end

app/views/users/_form.html.erb
<%= form_for(user) do |f| %>
  <div class="row">
    <div class="col-lg-4 col-md-6 col-sm-12">
      <div class="field">
        <%= f.label :name %>
        <%= f.text_field :name, class: "form-control" %>
      </div>
    </div>
    <div class="col-md-6 col-sm-0"></div>

    <div class="col-lg-6 col-md-8 col-sm-12">
      <div class="field">
        <%= f.label :password %>
        <%= f.password_field :password, class: "form-control" %>
      </div>
      <div class="field">
        <%= f.label :password_confirmation %>
        <%= f.password_field :password_confirmation, class: "form-control" %>
      </div>
    </div>
    <div class="col-lg-6 col-md-4 col-sm-0"></div>

    <div class="col-lg-2 col-md-2 col-sm-1"></div>
    <div class="col-lg-6 col-md-8 col-sm-10">
      <%= f.submit class: "btn btn-light btn-block blank" %>
    </div>
    <div class="col-lg-4 col-md-2 col-sm-1"></div>
  </div>
<% end %>

app/views/users/_login_form.html.erb
<%= form_tag login_path, method: :post do %>
  <div class="row">
    <div class="col-md-6 col-sm-12">
      <%= label_tag :name %>
      <%= text_field_tag :name, params[:name], class: "form-control" %>
    </div>
    <div class="col-sm-0"></div>
  </div>

  <div class="row mt-4">
    <div class="col-md-8 col-sm-12">
      <%= label_tag :password %>
      <%= password_field_tag :password, params[:password], class: "form-control" %>
    </div>
    <div class="col-md-4 col-sm-0"></div>
  </div>

  <div class="row mt-2">
    <div class="col-md-2 col-sm-1"></div>
    <div class="col-md-8 col-sm-10">
      <%= submit_tag "Log in", class: "btn btn-light btn-block blank" %>
    </div>
    <div class="col-md-2 col-sm-1"></div>
  </div>
<% end %>

app/views/users/_signup_form.html.erb
<%= form_for(user) do |f| %>
  <div class="row">
    <div class="col-md-6 col-sm-12">
      <%= f.label :name %>
      <%= f.text_field :name, class: "form-control" %>
    </div>
    <div class="col-md-6 col-sm-0"></div>
  </div>

  <div class="row">
    <div class="col-md-8 col-sm-12">
      <div class="field mt-3">
        <%= f.label :password %>
        <%= f.password_field :password, class: "form-control" %>
      </div>
      <div class="field mt-3">
        <%= f.label :password_confirmation %>
        <%= f.password_field :password_confirmation, class: "form-control" %>
      </div>
    </div>
    <div class="col-md-4 col-sm-0"></div>
  </div>

  <div class="row mt-2">
    <div class="col-md-2 col-sm-1"></div>
    <div class="col-md-8 col-sm-10">
      <%= f.submit class: "btn btn-light btn-block blank" %>
    </div>
    <div class="col-md-2 col-sm-1"></div>
  </div>
<% end %>

app/views/users/destroy_confirmation.html.erb
<% provide :title, "Really want to delete?" %>

<p>
  <strong>This operation is irreversible</strong>.
</p>
<p>
  Once you delete your account,
   all your uploaded memorandums will also deleted
   and cannot be restored.
  If you really want to delete, enter registered name in the form below.
</p>

<%= form_tag user_path(@user), method: :delete do %>
  <div class="row">
    <div class="col-lg-4 col-md-3 col-sm-2 col-1"></div>
    <div class="col-lg-4 col-md-6 col-sm-8 col-10">
      <%= text_field_tag :name_confirmation, '', class: "form-control" %>
      <%= submit_tag "Delete", class: "btn btn-light btn-block blank" %>
    </div>
    <div class="col-lg-4 col-md-3 col-sm-2 col-1"></div>
  </div>
<% end %>
<%= link_to 'Back', edit_user_path(@user) %>

app/views/users/edit.html.erb
<% provide :title, "Editing User" %>


<div class="row">
  <div class="col-lg-2"></div>

  <div class="col-lg-8">
    <%= render 'signup_form', user: @user %>

    <div class="row">
      <div class="col-md-2">
        <%= link_to 'Back', @user %>
      </div>
      <div class="col-md-8"></div>
      <div class="col-md-2 text-right">
        <%= link_to 'Delete', delete_user_path(@user) %>
      </div>
    </div>

  <div class="col-lg-2"></div>
</div>

app/views/users/enter.html.erb
<% provide :title, "Log in" %>


<div class="row">
  <div class="col-lg-2"></div>

  <div class="col-lg-8">
    <%= render 'login_form', user: @user %>

    <div class="row">
      <div class="col-md-2">
        <%= link_to 'Back', top_path %>
      </div>
      <div class="col-md-6"></div>
      <div class="col-md-4 text-right">
        <s>
        If you have no account,
        <%#= link_to 'Sign up', new_user_path %>
        Sign up
        </s>
      </div>
    </div>
  </div>

  <div class="col-lg-2"></div>
</div>

app/views/users/index.html.erb
<% provide :title, "Users" %>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= link_to 'Show', user %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/users/login.html.erb
<% provide :title, "Log in" %>

<%= render 'login_form', user: @user %>

<div class="row">
  <div class="col-md-2">
    <%= link_to 'Back', top_path %>
  </div>
  <div class="col-md-6"></div>
  <div class="col-md-4 text-right">
    If you have no account,
    <%= link_to 'Sign up', new_user_path %>
  </div>
</div>

app/views/users/new.html.erb
<% provide :title, "New User" %>

<div class="row">
  <div class="col-lg-2"></div>

  <div class="col-lg-8">
    <%= render 'signup_form', user: @user %>

    <%= link_to 'Back', login_path %>
  </div>

  <div class="col-lg-2"></div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>

<div class="row">
  <div class="col-md-4">
    <% if current_user?(@user) %>
      <%= link_to 'Edit profile', edit_user_path(@user) %> |
    <% end %>
    <%= link_to 'Back', users_path %>
  </div>
  <div class="col-md-8"></div>
</div>
<br>

<%= render 'shared/post_list', posts: @posts, user: @user %>