config/routes.rb
Rails.application.routes.draw do
  root 'posts#top'
  resources :users
  get '/login', to: 'users#enter', as: :login
  post '/login', to: 'users#login'
  delete '/logout', to: 'users#logout', as: :logout
  get '/users/(:id)/delete', to:'users#destroy_confirmation', as: :delete_user

  get '/top', to: 'posts#top', as: :top
  get '/posts/new', to: 'posts#new', as: :new_post
  post 'posts/new', to: 'posts#create'
  get '/posts/(:id)', to: 'posts#show', as: :post
  delete '/posts/(:id)', to: 'posts#destroy', as: :delete_post
  patch '/posts/(:id)', to: 'posts#update'
  get '/posts/(:id)/edit', to: 'posts#edit', as: :edit_post
  post '/readme', to: 'posts#readme', as: :readme
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/shared/_error_messages.html.erb
<% flash.each do |type, message| %>
  <% if message.present? %>
    <div class="alert alert-<%= type %>">
      <% if message.instance_of?(Array) %>
        <%= message.shift %>
        <% if message.length %>
          <ul>
            <% message.each do |msg| %>
              <li><%= msg %></li>
            <% end %>
          </ul>
        <% end %>
      <% else %>
        <%= message %>
      <% end %>
    </div>
  <% end %>
<% end %>

app/views/shared/_lower_pager.html.erb
<div class="row">
  <div class="col-md-2">
    <%= link_to action, action_url %> |
    <%= link_to 'Back', top_path %>
  </div>
  <div class="col-md-8"></div>
  <div class="col-md-2 text-right">
    <%= link_to 'Delete', @post, method: :delete, data: { confirm: 'Are you sure?' } %>
  </div>
</div>

app/views/shared/_post_list.html.erb
<% if posts.any? %>
  <%= render 'shared/post_list_pagination', posts: posts, user: user %>

  <div class="row post">
    <div class="col-md-4">
      <strong>Name</strong>
    </div>
    <div class="col-md-4">
      <strong>Original file</strong>
    </div>
    <div class="col-md-3">
      <strong>Posted at</strong>
    </div>
    <div class="col-md-1"></div>
  </div>

  <% posts.each do |post| %>
    <div class="row post">
      <div class="col-md-4">
        <%= link_to post.name, post_path(post), class: "break" %>
      </div>
      <div class="col-md-4">
          <%= link_to original_filename(post.memo.url), post.memo.url, class: "break" %>
      </div>
      <div class="col-md-3">
          <%= time_ago_in_words(post.created_at).capitalize %> ago
      </div>
      <div class="col-md-1">
        <% if of_current_user?(post) %>
          <%= link_to post, method: :delete, data: { confirm: 'Are you sure?' } do %>
            <span aria-hidden="true" class="text-danger">&times;</span>
          <% end %>
        <% end %>
      </div>
    </div>
  <% end %>

  <br>
  <%= render 'shared/post_list_pagination', posts: posts, user: user %>
<% else %>
  <p> There are no posts. </p>
<% end %>

app/views/shared/_post_list_pagination.html.erb
<div class="row">
  <div class="col-md-8 col-sm-6 col-xs-6">
    <%= will_paginate posts %>
  </div>
  <div class="col-md-4 col-sm-6 col-xs-6 text-right">
    <% if user.nil? || current_user?(user) %>
      <%= link_to 'New Post', new_post_path, class: "btn btn-dark new_post" %>
    <% end %>
  </div>
</div>