config/routes.rb
Rails.application.routes.draw do
  root 'posts#top'
  resources :users
  get '/login', to: 'users#enter', as: :login
  post '/login', to: 'users#login'
  delete '/logout', to: 'users#logout', as: :logout
  get '/users/(:id)/delete', to:'users#destroy_confirmation', as: :delete_user

  get '/top', to: 'posts#top', as: :top
  get '/posts/new', to: 'posts#new', as: :new_post
  post 'posts/new', to: 'posts#create'
  get '/posts/(:id)', to: 'posts#show', as: :post
  delete '/posts/(:id)', to: 'posts#destroy', as: :delete_post
  patch '/posts/(:id)', to: 'posts#update'
  get '/posts/(:id)/edit', to: 'posts#edit', as: :edit_post
  post '/readme', to: 'posts#readme', as: :readme
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <div class="container text-center">
    <p style="color:white;">
      Upload random memorandums
      for managing and utilising them!
    </p>
    <small style="color:white;">
      Daiji Tsutsui
    </small>
  </div>
</footer>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-md bg-dark navbar-dark fixed-top">
  <!-- Brand -->
  <%= link_to "RandomMemo", root_path, class: "navbar-brand" %>

  <!-- Navbar links -->
  <div class="collapse navbar-collapse" id="cl-list">
    <ul class="navbar-nav">
      <li class="nav-item">
        <%= link_to "NewPost", new_post_path, class: "nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to "ReadMe", readme_path, method: :post, class: "nav-link" %>
      </li>
      <li class="search_form">
        <%= form_tag top_path, method: :get do %>
          <%= text_field_tag :word, '', class: "form-control search_box" %>
        <% end %>
      </li>
      <!-- <li class="nav-item"> -->
        <%#= link_to "Users", users_path, class: "nav-link" %>
      <!-- </li> -->
    </ul>
  </div>

  <ul class="nav justify-content-end">
    <% if logged_in? %>
      <li class="nav-item">
        <%= link_to current_user.name, user_path(current_user), class: "nav-link" %>
      </li>
      <li>
        <%= link_to "Log out", logout_path, method: :delete, class: "nav-link" %>
      </li>
    <% else %>
      <!-- <li> -->
        <%#= link_to "Log in", login_path, class: "nav-link" %>
      <!-- </li> -->
    <% end %>
    <li>
      <!-- Toggler/collapsibe Button -->
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#cl-list">
        <span class="navbar-toggler-icon"></span>
      </button>
    </li>
  </ul>
</nav>
<div style="height:50px;"></div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RandomMemo</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container-fluid">
      <%= render 'layouts/header' %>
      <div class="jumbotron text-center h1">
        <%= yield(:title) %>
      </div>
      <%= render 'shared/error_messages' %>
      <article class="container">
        <%= yield %>
      </article>
      <%= render 'layouts/footer' %>
    </div>
  </body>
</html>